import os
import tempfile
from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types
from agents.instagram_poster import instagram_poster_agent

router = APIRouter(prefix="/instagram", tags=["Instagram"])

APP_NAME = "instagram_pipeline"
USER_ID = "user123"

session_service = InMemorySessionService()
runner = Runner(
    agent=instagram_poster_agent,
    app_name=APP_NAME,
    session_service=session_service
)


@router.post("/post")
async def post_to_instagram(image: UploadFile = File(...), caption: str = Form("")):
    """
    Post an image to Instagram with optional caption.
    Generates caption if not provided.
    """
    if not image:
        raise HTTPException(status_code=400, detail="No file uploaded")

    if not image.content_type.startswith('image/'):
        raise HTTPException(status_code=400, detail="File must be an image")

    temp_path = None

    try:
        # Save uploaded file temporarily
        filename = image.filename or "upload.jpg"
        ext = os.path.splitext(filename)[1] or ".jpg"

        with tempfile.NamedTemporaryFile(delete=False, suffix=ext) as temp_file:
            content = await image.read()
            temp_file.write(content)
            temp_path = temp_file.name

        print(f"Received file: {temp_path}, Caption: {caption}")

        # Create unique session for this request
        session_id = f"session_{os.urandom(8).hex()}"
        await session_service.create_session(
            app_name=APP_NAME,
            user_id=USER_ID,
            session_id=session_id
        )

        # Send message to agent
        message = types.Content(
            role="user",
            parts=[types.Part(
                text=f"Post this image to Instagram. Image path: {temp_path}, Caption: {caption}"
            )]
        )

        result_text = ""
        generated_caption = caption

        # Run agent asynchronously
        async for event in runner.run_async(
            user_id=USER_ID,
            session_id=session_id,
            new_message=message
        ):
            if event.is_final_response():
                result_text = event.content.parts[0].text
                print("Agent response:", result_text)

        if not result_text:
            raise HTTPException(status_code=500, detail="Failed to post to Instagram")

        return {
            "success": True,
            "caption": generated_caption if generated_caption else "Caption generated by AI",
            "post_result": result_text,
            "message": "Successfully posted to Instagram"
        }

    except Exception as e:
        print(f"Error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error posting to Instagram: {str(e)}")

    finally:
        # Clean up temporary file
        if temp_path and os.path.exists(temp_path):
            try:
                os.remove(temp_path)
                print(f"Cleaned up: {temp_path}")
            except OSError:
                pass